# Generated by Django 4.2.6 on 2023-10-27 03:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emissions', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emission',
            name='scope1',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='emission',
            name='scope2',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='emission',
            name='scope3',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
